### ISSUE TITLE
Season 7 + PlugY

### ISSUE THREAD

**Issue by Otsepov** [BetweenWalls/PD2-PlugY#1]
Recentle there was an unpade of PD2 to season 7. It comes with the vido feature of somewhat. So probably because of taht or whatever but plugy not working at all. Game launces - you are choosing the character. But error occures. 
![image](https://user-images.githubusercontent.com/53227775/235347759-66bf356d-de1c-4dd8-ba59-b92509f54b89.png)

**Comment by tandrasi** [comment]
This is fixed in latest update. Give it a go!
